-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('item_pb')


local ITEM = protobuf.Descriptor();
local ITEM_ID_FIELD = protobuf.FieldDescriptor();
local ITEM_TYPE_FIELD = protobuf.FieldDescriptor();
local ITEM_AMOUNT_FIELD = protobuf.FieldDescriptor();
local LOAD_ITEM = protobuf.Descriptor();
local LOAD_ITEM_ITEMS_FIELD = protobuf.FieldDescriptor();

ITEM_ID_FIELD.name = "id"
ITEM_ID_FIELD.full_name = ".item.id"
ITEM_ID_FIELD.number = 1
ITEM_ID_FIELD.index = 0
ITEM_ID_FIELD.label = 1
ITEM_ID_FIELD.has_default_value = false
ITEM_ID_FIELD.default_value = 0
ITEM_ID_FIELD.type = 13
ITEM_ID_FIELD.cpp_type = 3

ITEM_TYPE_FIELD.name = "type"
ITEM_TYPE_FIELD.full_name = ".item.type"
ITEM_TYPE_FIELD.number = 2
ITEM_TYPE_FIELD.index = 1
ITEM_TYPE_FIELD.label = 1
ITEM_TYPE_FIELD.has_default_value = false
ITEM_TYPE_FIELD.default_value = 0
ITEM_TYPE_FIELD.type = 13
ITEM_TYPE_FIELD.cpp_type = 3

ITEM_AMOUNT_FIELD.name = "amount"
ITEM_AMOUNT_FIELD.full_name = ".item.amount"
ITEM_AMOUNT_FIELD.number = 3
ITEM_AMOUNT_FIELD.index = 2
ITEM_AMOUNT_FIELD.label = 1
ITEM_AMOUNT_FIELD.has_default_value = false
ITEM_AMOUNT_FIELD.default_value = 0
ITEM_AMOUNT_FIELD.type = 13
ITEM_AMOUNT_FIELD.cpp_type = 3

ITEM.name = "item"
ITEM.full_name = ".item"
ITEM.nested_types = {}
ITEM.enum_types = {}
ITEM.fields = {ITEM_ID_FIELD, ITEM_TYPE_FIELD, ITEM_AMOUNT_FIELD}
ITEM.is_extendable = false
ITEM.extensions = {}
LOAD_ITEM_ITEMS_FIELD.name = "items"
LOAD_ITEM_ITEMS_FIELD.full_name = ".load_item.items"
LOAD_ITEM_ITEMS_FIELD.number = 1
LOAD_ITEM_ITEMS_FIELD.index = 0
LOAD_ITEM_ITEMS_FIELD.label = 3
LOAD_ITEM_ITEMS_FIELD.has_default_value = false
LOAD_ITEM_ITEMS_FIELD.default_value = {}
LOAD_ITEM_ITEMS_FIELD.message_type = ITEM
LOAD_ITEM_ITEMS_FIELD.type = 11
LOAD_ITEM_ITEMS_FIELD.cpp_type = 10

LOAD_ITEM.name = "load_item"
LOAD_ITEM.full_name = ".load_item"
LOAD_ITEM.nested_types = {}
LOAD_ITEM.enum_types = {}
LOAD_ITEM.fields = {LOAD_ITEM_ITEMS_FIELD}
LOAD_ITEM.is_extendable = false
LOAD_ITEM.extensions = {}

item = protobuf.Message(ITEM)
load_item = protobuf.Message(LOAD_ITEM)

