-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('test_pb')


local TEST = protobuf.Descriptor();
local TEST_V_FIELD = protobuf.FieldDescriptor();
local TEST_X_FIELD = protobuf.FieldDescriptor();

TEST_V_FIELD.name = "v"
TEST_V_FIELD.full_name = ".test.v"
TEST_V_FIELD.number = 1
TEST_V_FIELD.index = 0
TEST_V_FIELD.label = 3
TEST_V_FIELD.has_default_value = false
TEST_V_FIELD.default_value = {}
TEST_V_FIELD.type = 5
TEST_V_FIELD.cpp_type = 1

TEST_X_FIELD.name = "x"
TEST_X_FIELD.full_name = ".test.x"
TEST_X_FIELD.number = 2
TEST_X_FIELD.index = 1
TEST_X_FIELD.label = 3
TEST_X_FIELD.has_default_value = false
TEST_X_FIELD.default_value = {}
TEST_X_FIELD.type = 9
TEST_X_FIELD.cpp_type = 9

TEST.name = "test"
TEST.full_name = ".test"
TEST.nested_types = {}
TEST.enum_types = {}
TEST.fields = {TEST_V_FIELD, TEST_X_FIELD}
TEST.is_extendable = false
TEST.extensions = {}

test = protobuf.Message(TEST)

